name: Dadirug.es forked this Markdown to HTML with GitHub Style GH Action
description: An action to convert Markdown files to HTML via GitHub's API with embedded GitHub CSS style.
branding:
  icon: code
  color: red
inputs:
  path:
    description: A comma-separated list of one or more paths to markdown files to convert, relative to the root of your project.
    required: true
  outputpath:
    description: Path to a folder where HTML files should be saved. By default, HTML files will be saved in the same path as the source markdown file.
    required: false
  matchpathstructure:
    description: If set to `true`, will output files into the path provided to `outputfolder` while preserving the directory structure of the input files. I.E. if `path` is `README.md,docs/Doc1.md` and `outputfolder` is `out`, the files created will be `out/README.html` and `out/docs/Doc1.html` rather than both files being created in the root of `out`.
    required: false
runs:
  using: composite
  steps:
    - name: Validate Inputs
      id: validate
      run: . "$env:GITHUB_ACTION_PATH\src\steps\1_validate.ps1"
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_OUTPUTPATH: ${{ inputs.outputpath }}
        INPUT_MATCHPATHSTRUCTURE: ${{ inputs.matchpathstructure }}
      shell: pwsh
    - name: Convert Files
      id: convert
      run: . "$env:GITHUB_ACTION_PATH\src\steps\2_convert.ps1"
      shell: pwsh
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_OUTPUTPATH: ${{ inputs.outputpath }}
        INPUT_MATCHPATHSTRUCTURE: ${{ inputs.matchpathstructure }}
